### ISSUE TITLE
Errors running SignalIntegrity GUI Python 3.12, numpy==2.0.0

### ISSUE THREAD

**Issue by dracid** [Nubis-Communications/SignalIntegrity#81]
After installing Signal Integrity App and trying to run, getting the following error message:
```(spyder-env) dracid@acid-framework:~/Documents/openSI/SignalIntegrity-1.4.1$ SignalIntegrity
Traceback (most recent call last):
  File "/home/dracid/spyder-env/bin/SignalIntegrity", line 5, in <module>
    from SignalIntegrity.App.SignalIntegrityApp import main
  File "/home/dracid/Documents/openSI/SignalIntegrity-1.4.1/SignalIntegrity/App/__init__.py", line 21, in <module>
    from .SignalIntegrityApp import SignalIntegrityApp
  File "/home/dracid/Documents/openSI/SignalIntegrity-1.4.1/SignalIntegrity/App/SignalIntegrityApp.py", line 38, in <module>
    from SignalIntegrity.Lib.ToSI import ToSI
  File "/home/dracid/Documents/openSI/SignalIntegrity-1.4.1/SignalIntegrity/Lib/__init__.py", line 22, in <module>
    from . import SystemDescriptions as sd
  File "/home/dracid/Documents/openSI/SignalIntegrity-1.4.1/SignalIntegrity/Lib/SystemDescriptions/__init__.py", line 21, in <module>
    from .SystemDescription import *
  File "/home/dracid/Documents/openSI/SignalIntegrity-1.4.1/SignalIntegrity/Lib/SystemDescriptions/SystemDescription.py", line 23, in <module>
    from SignalIntegrity.Lib.Devices import Tee
  File "/home/dracid/Documents/openSI/SignalIntegrity-1.4.1/SignalIntegrity/Lib/Devices/__init__.py", line 28, in <module>
    from .SeriesC import SeriesC
  File "/home/dracid/Documents/openSI/SignalIntegrity-1.4.1/SignalIntegrity/Lib/Devices/SeriesC.py", line 21, in <module>
    from numpy import math
ImportError: cannot import name 'math' from 'numpy' (/home/dracid/spyder-env/lib/python3.12/site-packages/numpy/__init__.py). Did you mean: 'emath'?
```

Running Ubuntu Linux 24.04, Python 3.12, Numpy numpy==2.0.0, SignalIntegrityApp 1.4.1

Searching online, seems Numpy 2.0 has deprecated .math part of the library. Perhaps that can be the reason?

**Comment by dracid** [comment]
Seems like the following several files need to be edited to import "pi" instead of "math" and it works great after:
![image](https://github.com/user-attachments/assets/3f58e947-6186-4f3c-afce-cdbf9d6b4bd3)

**Comment by Phi-sqrd** [comment]
@dracid , your initial post suggested modifying only the use of pi, but on my system (macOS Monterey 12.3.1), I found it necessary to update both pi and sqrt to maintain functionality.

**Changes Made**

I modified the following five files, which are named after the functions defined within them:

```
SeriesRse.py
SeriesL.py
SeriesC.py
TerminationC.py
TerminationL.py
```
In each file:

- Removed the import statement for math.
- Imported pi and sqrt directly from numpy.

```
from numpy import pi
from numpy import sqrt
```

- Replaced instances of math.pi and math.sqrt with the newly imported pi and sqrt.

Thanks to @dracid for the fix! the App works!

**Comment by dracid** [comment]
Thanks, glad this helped!! I hope I can create a pull request :)) Need to learn how to do this.

My bad, you are totally right --> math.sqrt also had to be replaced.

**Comment by Phi-sqrd** [comment]
That was incredibly helpful @dracid ! Thank you so much. I'm really looking forward to trying out the code with your PR.

**Comment by PetePupalaikis** [comment]
I merged this into InNextRelease after making some small changes.  Please mark this as closed if you agree.
